# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e2ee7dba3294e8acd2c79df7982140e53fee55adafcac27762dfb13b6756fd5639ee58d6263c5ddd21b14271e28adba35488c73f6a724dfc220c9f3cd536912

test:
  secret_key_base: 8cabdeef1d7d33785988371e9b0089ab63b9170d063ce2063a33675596d6ee7ae4c548e65dff051a17f3ee9bfbeeb60bf7c8c25f093b7935aaa3ae27d6c0ebac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
